name: flutter_recruitment_task
description: Flutter recruitment task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  rxdart: ^0.27.3

  freezed_annotation: ^1.0.0
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0

  animations: ^2.0.2
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.5
  mockito: ^5.0.15
  freezed: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#c0e8ee"
  image: assets/splash.png
  android: true
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"


